### PR TITLE
Context settings

### PR DESCRIPTION
**Pull request by astaric**

### CODE REVIEW

**Comment by astaric** [comment]
Hello World!

**Comment by astaric** [comment]
Hello World!

**Comment by astaric** [comment]
Hello World!

**Comment by astaric** [comment]
Anze was here again

**Comment by astaric** [comment]
Hi all

**Comment by astaric** [comment]
Hi all

**Comment by astaric** [comment]
Hi all

**Comment by astaric** [comment]
My header
Hi all

**Comment by astaric** [comment]
## Lint approves ##

```
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |5      |5        |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |2      |2        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|unused-variable          |1           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+
|bad-continuation         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 8.00/10 (previous run: 8.00/10, +0.00)


```

**Comment by astaric** [comment]
... PyLintResult
##Lint Approves

```
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |5      |5        |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |2      |2        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|unused-variable          |1           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+
|bad-continuation         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 8.00/10 (previous run: 8.00/10, +0.00)


```

**Comment by astaric** [comment]
##Lint Approves

```
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |5      |5        |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |2      |2        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|unused-variable          |1           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+
|bad-continuation         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 8.00/10 (previous run: 8.00/10, +0.00)


```

**Comment by astaric** [comment]
## Lint Approves

```
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |4      |4        |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |1      |1        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)


```

**Comment by biolab-helper** [comment]
## Lint Approves

```
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |4      |4        |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |1      |1        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)


```

**Comment by biolab-helper** [comment]
Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |4      |9        |-5.00      |
+-----------+-------+---------+-----------+
|refactor   |1      |13       |-12.00     |
+-----------+-------+---------+-----------+
|warning    |1      |20       |-19.00     |
+-----------+-------+---------+-----------+
|error      |0      |2        |-2.00      |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|missing-docstring        |3           |
+-------------------------+------------+
|too-many-public-methods  |1           |
+-------------------------+------------+
|too-many-lines           |1           |
+-------------------------+------------+
|missing-format-attribute |1           |
+-------------------------+------------+
|locally-disabled         |1           |
+-------------------------+------------+



Global evaluation
-----------------
Your code has been rated at 6.00/10 (previous run: 9.03/10, -3.03)

**Comment by biolab-helper** [comment]
<h2>Messages</h2>
<table>
<tr class="header">
<th>category</th>
<th>module</th>
<th>obj</th>
<th>line</th>
<th>column</th>
<th>msg</th>
</tr>
<tr class="even">
<td>info</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>351</td>
<td>0</td>
<td>Locally disabling broad-except (W0703)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>1</td>
<td>0</td>
<td>Too many lines in module (1118/1000)</td>
</tr>
<tr class="even">
<td>warning</td>
<td>Orange.widgets.settings</td>
<td>SettingsHandler._get_settings_filename</td>
<td>401</td>
<td>28</td>
<td>Missing format attribute '__qualname__' in format specifier '0.__qualname__'</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler.settings_from_widget.packer</td>
<td>726</td>
<td>8</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>refactor</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler</td>
<td>538</td>
<td>0</td>
<td>Too many public methods (21/20)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1084</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1088</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
</table>
</div>
</div>
</body>
</html>
<html>
<body>
<div>
<h1>Report</h1>
<p>538 statements analysed.</p><div>
<h2>Statistics by type</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>old number</th>
<th>difference</th>
<th>%documented</th>
<th>%badname</th>
</tr>
<tr class="even">
<td>module</td>
<td>1</td>
<td>1</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>class</td>
<td>10</td>
<td>10</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>method</td>
<td>78</td>
<td>78</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>function</td>
<td>3</td>
<td>3</td>
<td>=</td>
<td>0.00</td>
<td>0.00</td>
</tr>
</table>
</div>
<div>
<h2>External dependencies</h2>
<pre>Orange 
  \-data 
  | \-Domain (Orange.widgets.settings)
  | \-Variable (Orange.widgets.settings)
  \-misc 
  | \-environ (Orange.widgets.settings)
  \-util (Orange.widgets.settings)
  \-widgets 
    \-utils (Orange.widgets.settings)</pre></div>
<div>
<h2>Raw metrics</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>%</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>code</td>
<td>613</td>
<td>54.73</td>
<td>613</td>
<td>=</td>
</tr>
<tr class="odd">
<td>docstring</td>
<td>325</td>
<td>29.02</td>
<td>325</td>
<td>=</td>
</tr>
<tr class="even">
<td>comment</td>
<td>13</td>
<td>1.16</td>
<td>13</td>
<td>=</td>
</tr>
<tr class="odd">
<td>empty</td>
<td>169</td>
<td>15.09</td>
<td>169</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Duplication</h2>
<table>
<tr class="header">
<th>&#160;</th>
<th>now</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<th>nb duplicated lines</th>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
<tr class="odd">
<th>percent duplicated lines</th>
<td>0.000</td>
<td>0.000</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages by category</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>convention</td>
<td>4</td>
<td>4</td>
<td>=</td>
</tr>
<tr class="odd">
<td>refactor</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="even">
<td>warning</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="odd">
<td>error</td>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages</h2>
<table>
<tr class="header">
<th>message id</th>
<th>occurrences</th>
</tr>
<tr class="even">
<td>missing-docstring</td>
<td>3</td>
</tr>
<tr class="odd">
<td>too-many-public-methods</td>
<td>1</td>
</tr>
<tr class="even">
<td>too-many-lines</td>
<td>1</td>
</tr>
<tr class="odd">
<td>missing-format-attribute</td>
<td>1</td>
</tr>
<tr class="even">
<td>locally-disabled</td>
<td>1</td>
</tr>
</table>
</div>
<div>
<h2>Global evaluation</h2>
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)</div>
</div>
</body>
</html>

**Comment by biolab-helper** [comment]
<h2>Messages</h2>
<table>
<tr class="header">
<th>category</th>
<th>module</th>
<th>obj</th>
<th>line</th>
<th>column</th>
<th>msg</th>
</tr>
<tr class="even">
<td>info</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>351</td>
<td>0</td>
<td>Locally disabling broad-except (W0703)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>1</td>
<td>0</td>
<td>Too many lines in module (1118/1000)</td>
</tr>
<tr class="even">
<td>warning</td>
<td>Orange.widgets.settings</td>
<td>SettingsHandler._get_settings_filename</td>
<td>401</td>
<td>28</td>
<td>Missing format attribute '__qualname__' in format specifier '0.__qualname__'</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler.settings_from_widget.packer</td>
<td>726</td>
<td>8</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>refactor</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler</td>
<td>538</td>
<td>0</td>
<td>Too many public methods (21/20)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1084</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1088</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
</table>
</div>
</div>
</body>
</html>
<html>
<body>
<div>
<h1>Report</h1>
<p>538 statements analysed.</p><div>
<h2>Statistics by type</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>old number</th>
<th>difference</th>
<th>%documented</th>
<th>%badname</th>
</tr>
<tr class="even">
<td>module</td>
<td>1</td>
<td>1</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>class</td>
<td>10</td>
<td>10</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>method</td>
<td>78</td>
<td>78</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>function</td>
<td>3</td>
<td>3</td>
<td>=</td>
<td>0.00</td>
<td>0.00</td>
</tr>
</table>
</div>
<div>
<h2>External dependencies</h2>
<pre>Orange 
  \-data 
  | \-Domain (Orange.widgets.settings)
  | \-Variable (Orange.widgets.settings)
  \-misc 
  | \-environ (Orange.widgets.settings)
  \-util (Orange.widgets.settings)
  \-widgets 
    \-utils (Orange.widgets.settings)</pre></div>
<div>
<h2>Raw metrics</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>%</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>code</td>
<td>613</td>
<td>54.73</td>
<td>613</td>
<td>=</td>
</tr>
<tr class="odd">
<td>docstring</td>
<td>325</td>
<td>29.02</td>
<td>325</td>
<td>=</td>
</tr>
<tr class="even">
<td>comment</td>
<td>13</td>
<td>1.16</td>
<td>13</td>
<td>=</td>
</tr>
<tr class="odd">
<td>empty</td>
<td>169</td>
<td>15.09</td>
<td>169</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Duplication</h2>
<table>
<tr class="header">
<th>&#160;</th>
<th>now</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<th>nb duplicated lines</th>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
<tr class="odd">
<th>percent duplicated lines</th>
<td>0.000</td>
<td>0.000</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages by category</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>convention</td>
<td>4</td>
<td>4</td>
<td>=</td>
</tr>
<tr class="odd">
<td>refactor</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="even">
<td>warning</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="odd">
<td>error</td>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages</h2>
<table>
<tr class="header">
<th>message id</th>
<th>occurrences</th>
</tr>
<tr class="even">
<td>missing-docstring</td>
<td>3</td>
</tr>
<tr class="odd">
<td>too-many-public-methods</td>
<td>1</td>
</tr>
<tr class="even">
<td>too-many-lines</td>
<td>1</td>
</tr>
<tr class="odd">
<td>missing-format-attribute</td>
<td>1</td>
</tr>
<tr class="even">
<td>locally-disabled</td>
<td>1</td>
</tr>
</table>
</div>
<div>
<h2>Global evaluation</h2>
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)</div>
</div>
</body>
</html>

**Comment by biolab-helper** [comment]
<h2>Messages</h2>
<table>
<tr class="header">
<th>category</th>
<th>module</th>
<th>obj</th>
<th>line</th>
<th>column</th>
<th>msg</th>
</tr>
<tr class="even">
<td>info</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>351</td>
<td>0</td>
<td>Locally disabling broad-except (W0703)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>1</td>
<td>0</td>
<td>Too many lines in module (1118/1000)</td>
</tr>
<tr class="even">
<td>warning</td>
<td>Orange.widgets.settings</td>
<td>SettingsHandler._get_settings_filename</td>
<td>401</td>
<td>28</td>
<td>Missing format attribute '__qualname__' in format specifier '0.__qualname__'</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler.settings_from_widget.packer</td>
<td>726</td>
<td>8</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>refactor</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler</td>
<td>538</td>
<td>0</td>
<td>Too many public methods (21/20)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1084</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1088</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
</table>
</div>
</div>
</body>
</html>
<html>
<body>
<div>
<h1>Report</h1>
<p>538 statements analysed.</p><div>
<h2>Statistics by type</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>old number</th>
<th>difference</th>
<th>%documented</th>
<th>%badname</th>
</tr>
<tr class="even">
<td>module</td>
<td>1</td>
<td>1</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>class</td>
<td>10</td>
<td>10</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>method</td>
<td>78</td>
<td>78</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>function</td>
<td>3</td>
<td>3</td>
<td>=</td>
<td>0.00</td>
<td>0.00</td>
</tr>
</table>
</div>
<div>
<h2>External dependencies</h2>
<pre>Orange 
  \-data 
  | \-Domain (Orange.widgets.settings)
  | \-Variable (Orange.widgets.settings)
  \-misc 
  | \-environ (Orange.widgets.settings)
  \-util (Orange.widgets.settings)
  \-widgets 
    \-utils (Orange.widgets.settings)</pre></div>
<div>
<h2>Raw metrics</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>%</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>code</td>
<td>613</td>
<td>54.73</td>
<td>613</td>
<td>=</td>
</tr>
<tr class="odd">
<td>docstring</td>
<td>325</td>
<td>29.02</td>
<td>325</td>
<td>=</td>
</tr>
<tr class="even">
<td>comment</td>
<td>13</td>
<td>1.16</td>
<td>13</td>
<td>=</td>
</tr>
<tr class="odd">
<td>empty</td>
<td>169</td>
<td>15.09</td>
<td>169</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Duplication</h2>
<table>
<tr class="header">
<th>&#160;</th>
<th>now</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<th>nb duplicated lines</th>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
<tr class="odd">
<th>percent duplicated lines</th>
<td>0.000</td>
<td>0.000</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages by category</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>convention</td>
<td>4</td>
<td>4</td>
<td>=</td>
</tr>
<tr class="odd">
<td>refactor</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="even">
<td>warning</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="odd">
<td>error</td>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages</h2>
<table>
<tr class="header">
<th>message id</th>
<th>occurrences</th>
</tr>
<tr class="even">
<td>missing-docstring</td>
<td>3</td>
</tr>
<tr class="odd">
<td>too-many-public-methods</td>
<td>1</td>
</tr>
<tr class="even">
<td>too-many-lines</td>
<td>1</td>
</tr>
<tr class="odd">
<td>missing-format-attribute</td>
<td>1</td>
</tr>
<tr class="even">
<td>locally-disabled</td>
<td>1</td>
</tr>
</table>
</div>
<div>
<h2>Global evaluation</h2>
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)</div>
</div>
</body>
</html>

**Comment by biolab-helper** [comment]
<h2>Messages</h2>
<table>
<tr class="header">
<th>category</th>
<th>module</th>
<th>obj</th>
<th>line</th>
<th>column</th>
<th>msg</th>
</tr>
<tr class="even">
<td>info</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>351</td>
<td>0</td>
<td>Locally disabling broad-except (W0703)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>1</td>
<td>0</td>
<td>Too many lines in module (1118/1000)</td>
</tr>
<tr class="even">
<td>warning</td>
<td>Orange.widgets.settings</td>
<td>SettingsHandler._get_settings_filename</td>
<td>401</td>
<td>28</td>
<td>Missing format attribute '__qualname__' in format specifier '0.__qualname__'</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler.settings_from_widget.packer</td>
<td>726</td>
<td>8</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>refactor</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler</td>
<td>538</td>
<td>0</td>
<td>Too many public methods (21/20)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1084</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1088</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
</table>
</div>
</div>
</body>
</html>
<html>
<body>
<div>
<h1>Report</h1>
<p>538 statements analysed.</p><div>
<h2>Statistics by type</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>old number</th>
<th>difference</th>
<th>%documented</th>
<th>%badname</th>
</tr>
<tr class="even">
<td>module</td>
<td>1</td>
<td>1</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>class</td>
<td>10</td>
<td>10</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>method</td>
<td>78</td>
<td>78</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>function</td>
<td>3</td>
<td>3</td>
<td>=</td>
<td>0.00</td>
<td>0.00</td>
</tr>
</table>
</div>
<div>
<h2>External dependencies</h2>
<pre>Orange 
  \-data 
  | \-Domain (Orange.widgets.settings)
  | \-Variable (Orange.widgets.settings)
  \-misc 
  | \-environ (Orange.widgets.settings)
  \-util (Orange.widgets.settings)
  \-widgets 
    \-utils (Orange.widgets.settings)</pre></div>
<div>
<h2>Raw metrics</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>%</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>code</td>
<td>613</td>
<td>54.73</td>
<td>613</td>
<td>=</td>
</tr>
<tr class="odd">
<td>docstring</td>
<td>325</td>
<td>29.02</td>
<td>325</td>
<td>=</td>
</tr>
<tr class="even">
<td>comment</td>
<td>13</td>
<td>1.16</td>
<td>13</td>
<td>=</td>
</tr>
<tr class="odd">
<td>empty</td>
<td>169</td>
<td>15.09</td>
<td>169</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Duplication</h2>
<table>
<tr class="header">
<th>&#160;</th>
<th>now</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<th>nb duplicated lines</th>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
<tr class="odd">
<th>percent duplicated lines</th>
<td>0.000</td>
<td>0.000</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages by category</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>convention</td>
<td>4</td>
<td>4</td>
<td>=</td>
</tr>
<tr class="odd">
<td>refactor</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="even">
<td>warning</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="odd">
<td>error</td>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages</h2>
<table>
<tr class="header">
<th>message id</th>
<th>occurrences</th>
</tr>
<tr class="even">
<td>missing-docstring</td>
<td>3</td>
</tr>
<tr class="odd">
<td>too-many-public-methods</td>
<td>1</td>
</tr>
<tr class="even">
<td>too-many-lines</td>
<td>1</td>
</tr>
<tr class="odd">
<td>missing-format-attribute</td>
<td>1</td>
</tr>
<tr class="even">
<td>locally-disabled</td>
<td>1</td>
</tr>
</table>
</div>
<div>
<h2>Global evaluation</h2>
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)</div>
</div>
</body>
</html>

**Comment by biolab-helper** [comment]
<h2>Messages</h2>
<table>
<tr class="header">
<th>category</th>
<th>module</th>
<th>obj</th>
<th>line</th>
<th>column</th>
<th>msg</th>
</tr>
<tr class="even">
<td>info</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>351</td>
<td>0</td>
<td>Locally disabling broad-except (W0703)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>&#160;</td>
<td>1</td>
<td>0</td>
<td>Too many lines in module (1118/1000)</td>
</tr>
<tr class="even">
<td>warning</td>
<td>Orange.widgets.settings</td>
<td>SettingsHandler._get_settings_filename</td>
<td>401</td>
<td>28</td>
<td>Missing format attribute '__qualname__' in format specifier '0.__qualname__'</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler.settings_from_widget.packer</td>
<td>726</td>
<td>8</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>refactor</td>
<td>Orange.widgets.settings</td>
<td>ContextHandler</td>
<td>538</td>
<td>0</td>
<td>Too many public methods (21/20)</td>
</tr>
<tr class="odd">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1084</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
<tr class="even">
<td>convention</td>
<td>Orange.widgets.settings</td>
<td>PerfectDomainContextHandler.encode_domain.encode</td>
<td>1088</td>
<td>12</td>
<td>Missing function docstring</td>
</tr>
</table>
</div>
</div>
</body>
</html>
<html>
<body>
<div>
<h1>Report</h1>
<p>538 statements analysed.</p><div>
<h2>Statistics by type</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>old number</th>
<th>difference</th>
<th>%documented</th>
<th>%badname</th>
</tr>
<tr class="even">
<td>module</td>
<td>1</td>
<td>1</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>class</td>
<td>10</td>
<td>10</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>method</td>
<td>78</td>
<td>78</td>
<td>=</td>
<td>100.00</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>function</td>
<td>3</td>
<td>3</td>
<td>=</td>
<td>0.00</td>
<td>0.00</td>
</tr>
</table>
</div>
<div>
<h2>External dependencies</h2>
<pre>Orange 
  \-data 
  | \-Domain (Orange.widgets.settings)
  | \-Variable (Orange.widgets.settings)
  \-misc 
  | \-environ (Orange.widgets.settings)
  \-util (Orange.widgets.settings)
  \-widgets 
    \-utils (Orange.widgets.settings)</pre></div>
<div>
<h2>Raw metrics</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>%</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>code</td>
<td>613</td>
<td>54.73</td>
<td>613</td>
<td>=</td>
</tr>
<tr class="odd">
<td>docstring</td>
<td>325</td>
<td>29.02</td>
<td>325</td>
<td>=</td>
</tr>
<tr class="even">
<td>comment</td>
<td>13</td>
<td>1.16</td>
<td>13</td>
<td>=</td>
</tr>
<tr class="odd">
<td>empty</td>
<td>169</td>
<td>15.09</td>
<td>169</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Duplication</h2>
<table>
<tr class="header">
<th>&#160;</th>
<th>now</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<th>nb duplicated lines</th>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
<tr class="odd">
<th>percent duplicated lines</th>
<td>0.000</td>
<td>0.000</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages by category</h2>
<table>
<tr class="header">
<th>type</th>
<th>number</th>
<th>previous</th>
<th>difference</th>
</tr>
<tr class="even">
<td>convention</td>
<td>4</td>
<td>4</td>
<td>=</td>
</tr>
<tr class="odd">
<td>refactor</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="even">
<td>warning</td>
<td>1</td>
<td>1</td>
<td>=</td>
</tr>
<tr class="odd">
<td>error</td>
<td>0</td>
<td>0</td>
<td>=</td>
</tr>
</table>
</div>
<div>
<h2>Messages</h2>
<table>
<tr class="header">
<th>message id</th>
<th>occurrences</th>
</tr>
<tr class="even">
<td>missing-docstring</td>
<td>3</td>
</tr>
<tr class="odd">
<td>too-many-public-methods</td>
<td>1</td>
</tr>
<tr class="even">
<td>too-many-lines</td>
<td>1</td>
</tr>
<tr class="odd">
<td>missing-format-attribute</td>
<td>1</td>
</tr>
<tr class="even">
<td>locally-disabled</td>
<td>1</td>
</tr>
</table>
</div>
<div>
<h2>Global evaluation</h2>
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)</div>
</div>
</body>
</html>

**Pull request merged**
